import { Document, Page, View, Text } from '@react-pdf/renderer';
import { RifairLogo } from './RifairLogo';
import { styles, colors, type, spacing } from '@/lib/pdf/design-system';

export const BiasAnalysisReport = ({ data, logoSrc }: { data: any, logoSrc?: string }) => {
  // Filter real bias issues (exclude "LACK OF INFORMATION" and placeholders)
  const realIssues = (data.issues || []).filter((issue: any) => {
    const hasContent = issue.explanation && !issue.explanation.includes('[Insert');
    const isRealBias = issue.tag !== 'LACK_OF_INFORMATION' && issue.score > 30;
    return hasContent && isRealBias;
  });
  
  const score = data.score || 0;
  const scoreColor = score > 70 ? colors.danger : score > 40 ? colors.warning : colors.success;

  return (
    <Document>
      {/* PAGE 1: Cover + Summary + Issues */}
      <Page size="A4" style={[styles.page, { backgroundColor: colors.redBg }]}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={{ ...type.display, color: colors.red }}>Bias Analysis</Text>
            <Text style={{ ...type.caption, marginTop: spacing.xs }}>
              {new Date(data.created_at).toLocaleDateString('en-IN', { 
                day: 'numeric', month: 'long', year: 'numeric' 
              })}
            </Text>
          </View>
          <RifairLogo width={100} src={logoSrc} />
        </View>

        {/* Analyzed Content + Score — side by side */}
        <View style={{ flexDirection: 'row', gap: spacing.xl, marginBottom: spacing.xl }}>
          <View style={{ flex: 1.2 }}>
            <Text style={type.caption}>Analyzed Content</Text>
            <Text style={{ ...type.body, marginTop: spacing.sm, color: colors.ink }}>
              {data.original_text?.substring(0, 280)}
              {data.original_text?.length > 280 ? '...' : ''}
            </Text>
          </View>
          
          <View style={{ alignItems: 'center', justifyContent: 'center' }}>
            <View style={[styles.scoreBadge, { backgroundColor: scoreColor }]}>
              <Text style={styles.scoreValue}>{score}</Text>
            </View>
            <Text style={styles.scoreLabel}>BIAS SCORE</Text>
            <Text style={{ 
              fontSize: 10, fontWeight: 600, color: scoreColor, marginTop: spacing.xs 
            }}>
              {score > 70 ? 'High Risk' : score > 40 ? 'Moderate' : 'Low Risk'}
            </Text>
          </View>
        </View>

        {/* Divider */}
        <View style={{ height: 0.5, backgroundColor: colors.cloud, marginBottom: spacing.xl }} />

        {/* Executive Summary — compact */}
        <View style={styles.section}>
          <Text style={type.h2}>Executive Summary</Text>
          <Text style={type.body}>
            {realIssues.length > 0 
              ? `This analysis detected ${realIssues.length} bias-related issue${realIssues.length > 1 ? 's' : ''} requiring attention. ${score > 70 ? 'Immediate revision is strongly recommended before publication.' : score > 40 ? 'Review and revise flagged content to ensure compliance.' : 'Minor adjustments suggested for optimal inclusivity.'}`
              : 'No significant bias detected. The content meets fair hiring standards with minimal risk.'}
          </Text>
        </View>

        {/* Detailed Findings — tight, no orphans */}
        {realIssues.length > 0 && (
          <View style={styles.section}>
            <Text style={type.h2}>Detailed Findings</Text>
            {realIssues.map((issue: any, i: number) => (
              <View key={i} style={styles.issueCard} wrap={false}>
                <View style={styles.issueHeader}>
                  <Text style={styles.issueTag}>SEVERITY {issue.score > 70 ? 'HIGH' : issue.score > 50 ? 'MEDIUM' : 'LOW'}</Text>
                  <Text style={{ ...type.caption, fontSize: 7, color: colors.silver }}>
                    {issue.tag.replace(/_/g, ' ')}
                  </Text>
                </View>
                <Text style={styles.issueBody}>{issue.explanation}</Text>
                {issue.rewrite && !issue.rewrite.includes('[') && (
                  <View style={styles.rewriteBlock}>
                    <Text style={styles.rewriteLabel}>SUGGESTED REWRITE</Text>
                    <Text style={styles.rewriteText}>{issue.rewrite}</Text>
                  </View>
                )}
              </View>
            ))}
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Confidential • rifair.ai</Text>
          <Text style={styles.footerText}>Generated by Rifair AI</Text>
          <Text style={styles.footerText}>Page 1</Text>
        </View>
      </Page>

      {/* PAGE 2: Methodology (only if content exists) */}
      {realIssues.length > 0 && (
        <Page size="A4" style={styles.page}>
          <View style={styles.header}>
            <Text style={type.h1}>Methodology & Compliance</Text>
            <RifairLogo width={80} src={logoSrc} />
          </View>

          <View style={styles.section}>
            <Text style={type.h2}>Detection Approach</Text>
            <Text style={type.body}>
              Rifair AI employs a 3-layer hybrid detection system: (1) Pattern matching for instant identification of biased keywords and phrases, (2) Structural analysis to detect coded language and exclusionary framing, and (3) Semantic AI evaluation for contextual understanding of implicit bias.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={type.h2}>Legal Framework</Text>
            <Text style={type.body}>
              This analysis aligns with EEOC guidelines (US), Equality Act 2010 (UK), and Indian Constitutional provisions under Articles 14-16. For India-specific contexts, the Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, 1989 provisions are referenced where applicable.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={type.h2}>Recommended Actions</Text>
            <View style={{ gap: spacing.sm }}>
              {[
                'Review all flagged content with your legal/HR team',
                'Implement suggested rewrites before publishing',
                'Train interviewers on unconscious bias recognition',
                'Schedule quarterly audits of all hiring materials'
              ].map((item, i) => (
                <View key={i} style={{ flexDirection: 'row', gap: spacing.sm }}>
                  <Text style={{ color: colors.mint, fontWeight: 700 }}>•</Text>
                  <Text style={type.body}>{item}</Text>
                </View>
              ))}
            </View>
          </View>

          <View style={styles.footer} fixed>
            <Text style={styles.footerText}>Confidential • rifair.ai</Text>
            <Text style={styles.footerText}>Generated by Rifair AI</Text>
            <Text style={styles.footerText}>Page 2</Text>
          </View>
        </Page>
      )}
    </Document>
  );
};
