import { View, Text } from '@react-pdf/renderer';
import { styles } from '@/lib/pdf/styles';

export const PDFFooter = () => (
  <View style={styles.footer} fixed>
    <Text style={styles.footerText}>Confidential • Generated by Rifair AI</Text>
    <Text style={styles.footerLogo}>rifair</Text>
    <Text 
      style={styles.footerText} 
      render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} 
    />
  </View>
);
